environments:
  dev:
    url: http://dev.example.com
    name: Developer Setup
  prod:
    url: http://another.example.com
    name: My Cool App

#yaml list
my:
  servers:
    - dev.example.com
    - another.example.com